package qconstant

const (
	PassengerMatch               = "match"
	PassengerNoMatch             = "no match"
	PassengerTailgating          = "tailgating"
	PassengerPassportExpired     = "passport_expired"
	PassengerPassportExpiredSoon = "passport_expired_in_6months"
	PassengerMaxImmigrationCount = "max_immigration_count"
	PassengerMaxBoardingCount    = "max_boarding_count"
	PassengerMaxSCPCount         = "max_scp_count"
	PassengerGateNotMatch        = "gate_not_match"
	PassengerCannotBoard         = "cannot_board"
	PassengerPresent             = "passenger_present"
	PassengerEnrollMatch         = "passenger_enroll_match"
	PassengerEnrollNotMatch      = "passenger_enroll_not_match"
	PassengerNotPassedThrough    = "user_not_passed_through"
	PassengerTimeout             = "timeout"
)

const (
	PassengerStatusMatch               = "PassengerStatusMatch"
	PassengerStatusNoMatch             = "PassengerStatusNoMatch"
	PassengerStatusPresent             = "PassengerStatusPresent"
	PassengerStatusCheckin             = "PassengerStatusCheckin"
	PassengerStatusCheckinFailed       = "PassengerStatusCheckinFailed"
	PassengerStatusLeaveGate           = "PassengerStatusLeaveGate"
	PassengerStatusUpdatePassenger     = "PassengerStatusUpdatePassenger"
	PassengerStatusPassSCP             = "PassengerStatusPassSCP"
	PassengerStatusPassBoarding        = "PassengerStatusPassBoarding"
	PassengerStatusEnrollMatch         = "PassengerStatusEnrollMatch"
	PassengerStatusEnrollNotMatch      = "PassengerStatusEnrollNotMatch"
	PassengerStatusLowFaceScore        = "PassengerStatusLowFaceScore"
	PassengerStatusNotPassSCP          = "PassengerStatusNotPassSCP"
	PassengerStatusMaxSCPCount         = "PassengerStatusMaxSCPCount"
	PassengerStatusMaxImmigrationCount = "PassengerStatusMaxImmigrationCount"
	PassengerStatusMaxBoardingCount    = "PassengerStatusMaxBoardingCount"
	PassengerStatusPassportExpired     = "PassengerStatusPassportExpired"
	PassengerStatusPassportExpiredSoon = "PassengerStatusPassportExpiredSoon"
	PassengerStatusBoardNo             = "PassengerStatusBoardNo"
	PassengerStatusErrorBGR            = "PassengerStatusErrorBGR"
	PassengerStatusInvalidBCBP         = "PassengerStatusInvalidBCBP"
	PassengerStatusInvalidMRZ          = "PassengerStatusInvalidMRZ"
	PassengerStatusTailgating          = "PassengerStatusTailgating"
	PassengerStatusRevoked             = "PassengerStatusRevoked"
	PassengerStatusTimeout             = "PassengerStatusTimeout"
	PassengerStatusSpoof               = "PassengerStatusSpoof"
	PassengerStatusMask                = "PassengerStatusMask"
	PassengerStatusNotPassedThrough    = "PassengerStatusNotPassedThrough"
	PassengerStatusNameMissmatch       = "PassengerStatusNameMissmatch"
	PassengerStatusInternalError       = "PassengerStatusInternalError"
)
