package qconstant

const (
	PassengerMatch               = "match"
	PassengerNoMatch             = "no match"
	PassengerTailgating          = "tailgating"
	PassengerPassportExpired     = "passport_expired"
	PassengerPassportExpiredSoon = "passport_expired_in_6months"
	PassengerMaxImmigrationCount = "max_immigration_count"
	PassengerMaxBoardingCount    = "max_boarding_count"
	PassengerMaxSCPCount         = "max_scp_count"
	PassengerGateNotMatch        = "gate_not_match"
	PassengerCannotBoard         = "cannot_board"
	PassengerPresent             = "passenger_present"
	PassengerEnrollMatch         = "passenger_enroll_match"
	PassengerEnrollNotMatch      = "passenger_enroll_not_match"
	PassengerNotPassedThrough    = "user_not_passed_through"
	PassengerTimeout             = "timeout"
)

const (
	PassengerStatusMatch               = "match"
	PassengerStatusNoMatch             = "no_match"
	PassengerStatusPresent             = "present"
	PassengerStatusCheckin             = "checkin"
	PassengerStatusCheckinFailed       = "checkin_failed"
	PassengerStatusLeaveGate           = "leave_gate"
	PassengerStatusUpdatePassenger     = "update_passenger"
	PassengerStatusPassSCP             = "pass_scp"
	PassengerStatusPassBoarding        = "pass_boarding"
	PassengerStatusEnrollMatch         = "enroll_match"
	PassengerStatusEnrollNotMatch      = "enroll_not_match"
	PassengerStatusLowFaceScore        = "low_face_score"
	PassengerStatusNotPassSCP          = "not_pass_scp"
	PassengerStatusMaxSCPCount         = "max_scp_count"
	PassengerStatusMaxImmigrationCount = "max_immigration_count"
	PassengerStatusMaxBoardingCount    = "max_boarding_count"
	PassengerStatusPassportExpired     = "passport_expired"
	PassengerStatusPassportExpiredSoon = "passport_expired_in_6months"
	PassengerStatusBoardNo             = "board_no"
	PassengerStatusErrorBGR            = "error_bgr"
	PassengerStatusInvalidBCBP         = "invalid_bcbp"
	PassengerStatusInvalidMRZ          = "invalid_mrz"
	PassengerStatusTailgating          = "tailgating"
	PassengerStatusRevoked             = "revoked"
	PassengerStatusTimeout             = "timeout"
	PassengerStatusSpoof               = "spoof"
	PassengerStatusMask                = "mask"
	PassengerStatusNotPassedThrough    = "not_passed_through"
)
